---
apiVersion: v1
kind: Namespace
metadata:
  name: dotnetns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coreapitest
  namespace: dotnetns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapitest
  template:
    metadata:
      labels:
        app: coreapitest
    spec:
      containers:
        - name: coreapitest
          image: odedia/coreapitest
          env:
          - name: mongo_url
            value: mongodb://my-release-mongodb-replicaset-0.default.svc.cluster.local/sampledb
          - name: ControllerSettings__DbConfig__DbConnectionString
            value: mongodb://my-release-mongodb-replicaset-0.default.svc.cluster.local/sampledb  
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactsample
  namespace: dotnetns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactsample
  template:
    metadata:
      labels:
        app: reactsample
    spec:
      containers:
        - name: reactsample
          image: odedia/reactsample
          env:
          - name: REACT_APP_API_URL
            value: http://34.76.61.235/api/person
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactsample-lb
  labels:
    app: reactsample
  namespace: dotnetns
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: reactsample
---
apiVersion: v1
kind: Service
metadata:
  name: coreapitest-lb
  labels:
    app: coreapitest
  namespace: dotnetns
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: coreapitest
